sudo: required
language: python

python:
  - 2.7
  - 3.2

servicxes:
  - docker

install:
  - docker build -t heflik/opencv-container-linux .

script:
 - docker images | grep -q opencv-container-linux

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push geflik/opencv-container-linux
  fi

